# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  branches:
    master:
    - step:
        name: Deploy to production
        deployment: production
        script:
        - cat ./deployment/master.sh | ssh -T $user@$production_host sh
        - echo "Deploy started"
        - echo "Finally Deploy finished with success"

      # develop:
      #   - step:
      #       name: Deploy to staging
      #       deployment: staging
      #       script:
      #       - cat ./deployment/develop.sh | ssh -T $user@$dev_host sh
      #       - echo "Deploy step finished"
